# Generated by Django 5.2.16 on 2026-08-02 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_category_image_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="categories/",
                verbose_name="Загрузить фото",
            ),
        ),
        migrations.AddField(
            model_name="productimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="products/",
                verbose_name="Загрузить фото",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="image_url",
            field=models.URLField(
                blank=True, max_length=1000, null=True, verbose_name="Или URL картинки"
            ),
        ),
        migrations.AlterField(
            model_name="productimage",
            name="image_url",
            field=models.URLField(
                blank=True, max_length=1000, null=True, verbose_name="Или URL картинки"
            ),
        ),
    ]
