# Generated by Django 5.2.16 on 2026-08-03 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_category_image_productimage_image_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="description_uz",
            field=models.TextField(blank=True, verbose_name="Описание (UZ)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание (RU)"),
        ),
    ]
