# Generated by Django 5.2.16 on 2026-08-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_product_description_uz_alter_product_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="characteristics_uz",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Характеристики (UZ)"
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="characteristics",
            field=models.JSONField(
                blank=True, default=dict, verbose_name="Характеристики (RU)"
            ),
        ),
    ]
