# Generated by Django 5.2.16 on 2026-08-04 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0005_product_characteristics_uz_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="characteristics",
            field=models.TextField(blank=True, verbose_name="Характеристики (RU)"),
        ),
        migrations.AlterField(
            model_name="product",
            name="characteristics_uz",
            field=models.TextField(blank=True, verbose_name="Характеристики (UZ)"),
        ),
    ]
